version: '3.9'

services:
  postgres:
    container_name: postgres
    build: ./postgresql
    environment:
      - POSTGRES_USER=goblin
      - POSTGRES_PASSWORD=goblin
      - POSTGRES_DB=goblin
    ports:
      - '5555:5432'
    restart: always
    logging:
      options:
        max-size: '5m'
        max-file: '1'
    volumes:
      - goblin:/var/lib/postgresql/data

  redis:
    command: 'redis-server --port 6363'
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '127.0.0.1:6363:6363'
    restart: always
    logging:
      options:
        max-size: '5m'
        max-file: '1'
    volumes:
      - ./redis-data:/data

  bot:
    image: ghcr.io/r-priyam/goblin:latest
    container_name: goblin
    build:
      context: ../
    env_file:
      - ../src/.env
    depends_on:
      - postgres
      - redis
    restart: always
    logging:
      options:
        max-size: '100m'
        max-file: '3'
    tty: true

volumes:
  goblin:
  redis-data:
