name: Continuous Deployment
on:
  workflow_run:
    workflows:
      - Continuous Delivery
    types:
      - completed

jobs:
  deploy:
    name: Deploy bot image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip cd]')"
    steps:
      - name: Log In
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASSWORD }}
          command: |
            cd goblin
            npm run sync-docker
