name: Continuous Deployment
on:
  workflow_run:
    workflows:
      - Continuous Delivery
    types:
      - completed

jobs:
  deploy:
    name: Deploy bot image
    runs-on: ubuntu-latest
    steps:
      - name: Log In
        uses: appleboy/ssh-action@cc051b07ed0666619f6ea5703319edf00d06be13
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script_stop: true
          script: |
            cd goblin
            npm run sync-docker
