name: Continuous Deployment
on:
  workflow_run:
    workflows:
      - Continuous Delivery
    types:
      - completed

jobs:
  deploy:
    name: Deploy bot image
    runs-on: ubuntu-latest
    steps:
      - name: Log In
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script_stop: true
          script: |
            cd goblin
            npm run sync-docker
